### ISSUE TITLE
save/load context

### ISSUE THREAD

**Issue by biobootloader** [AbanteAI/mentat#521]
![image](https://github.com/AbanteAI/mentat/assets/128252497/01a4ead5-edb6-4eb1-b332-706062a7c03b)

**Comment by galer7** [comment]
Could this be a good first issue? I'm still reading the codebase but would love to try it out!

**Comment by jakethekoenig** [comment]
@galer7 sure, that would be great. The files included by the user are stored in `mentat/code_context.py` as `include_files`. I think adding save and load commands that accept an optional file name (otherwise maybe save to `~/.mentat/last_context.json`. You can see how commands are handled in `mentat/commands`. Feel free to ask questions here or on the discord

**Comment by galer7** [comment]
Thanks! I think I got a first naive solution done, will fix tests and formatting tomorrow
